const PLACEHOLDER_IMAGE ="https://nimc.gov.ng/assets/mdi-02-CZP-4uWs.png"
const ninSeeds = [
  {
    ninNumber: "12345678901",
    firstName: "Chukwuemeka",
    middleName: "Oluwaseun",
    lastName: "Adeyemi",
    dob: "15-03-1990",
    gender: "M",
    phone: "+2348012345678",
    email: "chukwu.adeyemi@example.com",
    residentialAddress: "15 Awolowo Road, Ikoyi, Lagos",
    stateOfOrigin: "Lagos",
    lga: "Lagos Island",
    height: "175cm",
    maritalStatus: "Single",
    image: PLACEHOLDER_IMAGE,
    enrollmentDate: "10-01-2015",
    status: "active"
  },
  {
    ninNumber: "22334455667",
    firstName: "Amina",
    middleName: "Fatima",
    lastName: "Ibrahim",
    dob: "22-07-1985",
    gender: "F",
    phone: "+2348089876543",
    email: "amina.ibrahim@example.com",
    residentialAddress: "42 Independence Way, Kaduna",
    stateOfOrigin: "Kaduna",
    lga: "Kaduna North",
    height: "162cm",
    maritalStatus: "Married",
    image: PLACEHOLDER_IMAGE,
    enrollmentDate: "05-03-2014",
    status: "active"
  },
  {
    ninNumber: "33445566778",
    firstName: "Obinna",
    middleName: null,
    lastName: "Okafor",
    dob: "01-12-1992",
    gender: "M",
    phone: "+2347711223344",
    email: "obinna.okafor@example.com",
    residentialAddress: "8 University Road, Enugu",
    stateOfOrigin: "Enugu",
    lga: "Enugu East",
    height: "180cm",
    maritalStatus: "Single",
    image: PLACEHOLDER_IMAGE,
    enrollmentDate: "18-06-2016",
    status: "active"
  },
  {
    ninNumber: "44556677889",
    firstName: "Ngozi",
    middleName: "Adaeze",
    lastName: "Eze",
    dob: "30-09-1988",
    gender: "F",
    phone: "+2348155554444",
    email: "ngozi.eze@example.com",
    residentialAddress: "120 Nnamdi Azikiwe Street, Onitsha",
    stateOfOrigin: "Anambra",
    lga: "Onitsha South",
    height: "158cm",
    maritalStatus: "Married",
    image: PLACEHOLDER_IMAGE,
    enrollmentDate: "20-02-2013",
    status: "active"
  },
  {
    ninNumber: "55667788990",
    firstName: "Emeka",
    middleName: "Sunday",
    lastName: "Nwosu",
    dob: "14-05-1995",
    gender: "M",
    phone: "+2349031112222",
    email: "emeka.nwosu@example.com",
    residentialAddress: "33 Aba Road, Port Harcourt",
    stateOfOrigin: "Rivers",
    lga: "Obio/Akpo",
    height: "172cm",
    maritalStatus: "Single",
    image: PLACEHOLDER_IMAGE,
    enrollmentDate: "07-11-2017",
    status: "active"
  }
];
module.exports=ninSeeds